# .github/workflows/tests.yaml
name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: |
            3.12
            ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3.12 -m pip install --upgrade pipx
          python3.12 -m pipx install nox
          python3.12 -m pipx install coverage
      - name: Test with pytest
        run: nox -p ${{ matrix.python-version }}
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          debug: true
          format: python
          flag-name: run-${{ join(matrix.*, '-') }}

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        #carryforward: "run-3.7,run-3.8,run-3.9,run-3.10,run-3.11"
